Repository ExpTechTW/DPIP, pull requests merged in 2024-08, with the labels that each got.

#213 fix: Location lacks regional
  assets/location.json
Labels: size/XS

#217 chore: Current dependent library version
  pubspec.lock
  pubspec.yaml
Labels: size/M

#221 fix: asynchronous sound test
  lib/widget/settings/sound/sound_list_tile.dart
Labels: size/M

#212 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_CN.arb
  lib/l10n/app_zh_TW.arb
Labels: size/L

#222 地圖置中
  lib/widget/map/map.dart
Labels: size/XS

#219 feat: report wave
  lib/route/report/report.dart
  lib/widget/map/map.dart
Labels: size/M

#225 chore: update readme
  .github/ISSUE_TEMPLATE/Bug.yml
  .github/assets/download_source.png
  .github/assets/splash.png
  README.md
Labels: size/L

#224 Fix: map zoom
  lib/widget/map/map.dart
  pubspec.yaml
Labels: size/S

#228 I18n dpip
  ios/Runner/Info.plist
  lib/app/page/me/me.dart
  lib/l10n/app_zh_TW.arb
  lib/route/locale_selector/locale_selector.dart
  lib/route/location_selector/location_selector.dart
  lib/route/report/report.dart
  lib/route/settings/content/root.dart
  lib/route/settings/content/sound.dart
Labels: size/L

#229 fix: location MonitorPage
  lib/route/location_selector/location_selector.dart
  pubspec.lock
  pubspec.yaml
Labels: size/M, android

#232 fix: delay counter style
  lib/app/page/monitor/monitor.dart
Labels: size/S

#230 fix: automatic location
  lib/core/location.dart
  lib/core/service.dart
Labels: size/XS, android

#233 feat: weather map
  assets/map/icons/wind-high.png
  assets/map/icons/wind-low.png
  assets/map/icons/wind-middle.png
  lib/api/exptech.dart
  lib/api/route.dart
  lib/app/dpip.dart
  lib/app/page/map/map.dart
  lib/app/page/map/radar/radar.dart
  lib/app/page/map/rain/rain.dart
  lib/app/page/map/tsunami.dart
  lib/app/page/map/tsunami/tsunami.dart
  lib/app/page/map/tsunami/tsunami_estimate_list.dart
  lib/app/page/map/tsunami/tsunami_observed_list.dart
  lib/app/page/map/typhoon/typhoon.dart
  lib/app/page/map/weather/humidity.dart
  lib/app/page/map/weather/pressure.dart
  lib/app/page/map/weather/temperature.dart
  lib/app/page/map/weather/wind.dart
  lib/app/page/me/me.dart
  lib/app/page/monitor/monitor.dart
  lib/core/eew.dart
  lib/core/ios_get_location.dart
  lib/core/rts.dart
  lib/core/service.dart
  lib/model/crowdin/localization_progress.dart
  lib/model/weather/rain.dart
  lib/model/weather/weather.dart
  lib/route/locale_selector/locale_selector.dart
  lib/route/report/report.dart
  lib/route/settings/settings.dart
  lib/util/map_utils.dart
  lib/widget/list/rain_time_selector.dart
  lib/widget/list/time_selector.dart
  lib/widget/map/map.dart
  pubspec.lock
  pubspec.yaml
Labels: size/XXL

#235 Fix monitor page
  lib/app/dpip.dart
  lib/app/page/map/map.dart
  lib/app/page/monitor/monitor.dart
Labels: size/M

#234 I18n.dpip
  lib/l10n/app_zh_TW.arb
  lib/route/settings/content/sound.dart
Labels: size/S

#227 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_CN.arb
  lib/l10n/app_zh_TW.arb
Labels: size/XXL

#239 Fix location
  lib/app/page/history/history.dart
  lib/app/page/home/home.dart
  lib/core/ios_get_location.dart
  lib/core/service.dart
  lib/route/location_selector/location_selector.dart
  lib/widget/error/region_out_of_service.dart
Labels: size/XL

#238 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh_CN.arb
Labels: size/XL

#242 fix: ios report image save
  lib/route/image_viewer/image_viewer.dart
  lib/route/report/report.dart
Labels: size/S

#241 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh_CN.arb
Labels: size/XXL

#245 i18n.dpip
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/vi.lproj/LaunchScreen.strings
  ios/Runner/vi.lproj/Main.strings
  lib/app/page/map/lightning/lightning.dart
  lib/app/page/map/monitor/monitor.dart
  lib/app/page/me/me.dart
  lib/l10n/app_zh_TW.arb
  lib/route/settings/content/location.dart
  pubspec.yaml
Labels: size/L

#247 fix: log
  lib/app/dpip.dart
  lib/app/page/map/monitor/monitor.dart
  lib/app/page/map/radar/radar.dart
  lib/app/page/map/rain/rain.dart
  lib/app/page/map/typhoon/typhoon.dart
  lib/app/page/map/weather/humidity.dart
  lib/app/page/map/weather/pressure.dart
  lib/app/page/map/weather/temperature.dart
  lib/app/page/map/weather/wind.dart
  lib/core/fcm.dart
  lib/core/ios_get_location.dart
  lib/core/location.dart
  lib/core/service.dart
  lib/route/log/log.dart
  lib/route/report/report.dart
  lib/route/settings/content/location.dart
  lib/route/welcome/pages/permission.dart
Labels: size/M

#249 fix: service
  lib/app/page/history/history.dart
  lib/app/page/home/home.dart
  lib/core/service.dart
  lib/model/history.dart
  lib/route/report/report.dart
  lib/util/list_icon.dart
Labels: size/M

#248 i18n_dpip
  lib/app/dpip.dart
  lib/app/page/map/tsunami/tsunami.dart
  lib/app/page/me/me.dart
  lib/l10n/app_zh_TW.arb
  lib/route/image_viewer/image_viewer.dart
  lib/route/log/log.dart
  lib/route/notification/notification.dart
  lib/route/report/report.dart
  lib/route/settings/content/location.dart
  lib/route/status/status.dart
  lib/route/update_required/update_required.dart
Labels: size/L

#250 i18n.dpip.3
  lib/app/page/home/home.dart
  lib/app/page/map/lightning/lightning.dart
  lib/app/page/map/monitor/monitor.dart
  lib/app/page/map/radar/radar.dart
  lib/app/page/map/rain/rain.dart
  lib/app/page/map/tsunami/tsunami.dart
  lib/app/page/map/weather/humidity.dart
  lib/app/page/map/weather/pressure.dart
  lib/app/page/map/weather/temperature.dart
  lib/app/page/me/me.dart
  lib/l10n/app_zh_TW.arb
  lib/route/notification/notification.dart
  lib/route/status/status.dart
Labels: size/L

#244 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_CN.arb
Labels: size/XXL

#254 fix: settings scrolling
  lib/route/settings/settings.dart
  lib/util/page_route_builder/forward_back.dart
Labels: size/L

#251 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_CN.arb
Labels: size/XXL

#258 chore: move donate button up
  lib/app/page/me/me.dart
Labels: size/M
