Repository ExpTechTW/DPIP, pull requests merged in 2024-09, with the labels that each got.

#260 refactor: report filter
  lib/app/page/more/more.dart
  lib/app/page/more/report_list/report_list.dart
  lib/l10n/app_zh_TW.arb
  lib/route/settings/content/location.dart
Labels: size/L

#261 I18n.dpip
  lib/app/page/home/home.dart
  lib/app/page/map/meteor.dart
  lib/app/page/more/report_list/report_list.dart
  lib/l10n/app_zh_TW.arb
  lib/route/event_viewer/intensity.dart
Labels: size/M

#255 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_CN.arb
Labels: size/XXL

#263 feat: ranking page
  lib/app/page/more/more.dart
  lib/app/page/more/ranking/ranking.dart
  lib/app/page/more/ranking/tabs/precipitation.dart
  lib/app/page/more/ranking/tabs/temperature.dart
  lib/app/page/more/ranking/tabs/wind.dart
  lib/l10n/app_zh_TW.arb
  lib/util/extension/color_scheme.dart
  lib/util/intervals.dart
  lib/util/parser.dart
  pubspec.yaml
Labels: size/XXL

#265 Fix temp rank
  lib/app/page/more/ranking/tabs/precipitation.dart
  lib/app/page/more/ranking/tabs/temperature.dart
  lib/app/page/more/ranking/tabs/wind.dart
  lib/app/page/more/report_list/report_list.dart
  lib/main.dart
  lib/widget/map/map.dart
Labels: size/M

#262 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_CN.arb
Labels: size/XXL

#266 Refactor sound test
  lib/api/exptech.dart
  lib/api/route.dart
  lib/app/page/map/typhoon/typhoon.dart
  lib/model/weather/typhoon.dart
  pubspec.yaml
Labels: size/L

#268 Icon Revamp
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: size/S

#269 Notification icon
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/ic_stat_name.png
  android/app/src/main/res/drawable-mdpi/ic_stat_name.png
  android/app/src/main/res/drawable-xhdpi/ic_stat_name.png
  android/app/src/main/res/drawable-xxhdpi/ic_stat_name.png
  android/app/src/main/res/drawable-xxxhdpi/ic_stat_name.png
  lib/core/notify.dart
Labels: size/XS, android

#270 i18n.dpip
  lib/app/page/more/ranking/tabs/precipitation.dart
  lib/app/page/more/ranking/tabs/temperature.dart
  lib/app/page/more/ranking/tabs/wind.dart
  lib/l10n/app_zh_TW.arb
  lib/route/welcome/pages/permission.dart
Labels: size/M

#271 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh_CN.arb
Labels: size/XL

#274 New Crowdin updates
  lib/l10n/app_ja.arb
  lib/l10n/app_zh_CN.arb
Labels: size/M

#275 fix: rain arrow icons
  lib/widget/list/rain_time_selector.dart
  lib/widget/list/time_selector.dart
  lib/widget/list/typhoon_time_selector.dart
Labels: size/XS

#276 feat: app name localization
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values-ja/strings.xml
  android/app/src/main/res/values-ko/strings.xml
  android/app/src/main/res/values-zh-rTW/strings.xml
  android/app/src/main/res/values-zh/strings.xml
  android/app/src/main/res/values/strings.xml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/ja.lproj/InfoPlist.strings
  ios/Runner/ko.lproj/InfoPlist.strings
  ios/Runner/zh-Hant.lproj/InfoPlist.strings
  ios/Runner/zh.lproj/InfoPlist.strings
Labels: size/M, android, ios

#277 fix: monitor warn card overflow for all
  lib/app/page/map/monitor/monitor.dart
Labels: size/XS

#278 New Crowdin updates
  lib/l10n/app_ja.arb
Labels: size/XS

#281 fix: iOS app name localization
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/zh_TW.lproj/InfoPlist.strings
  ios/Runner/zh_TW.lproj/LaunchScreen.strings
  ios/Runner/zh_TW.lproj/Main.strings
Labels: size/M, ios

#283 fix: tsunami-notify
  lib/core/notify.dart
Labels: size/XS

#282 fix: tsunami information layout
  lib/app/page/map/tsunami/tsunami.dart
Labels: size/S
