Repository ExpTechTW/DPIP, pull requests merged in 2024-04, with the labels that each got.

#28 fix: report
  .github/workflows/github_actions.yml
  ios/Podfile.lock
  lib/view/init.dart
  lib/view/report.dart
Labels: size/M

#31 chore: repo cleanup
  .gitignore
  lib/view/loc-set.dart
  linux/flutter/ephemeral/.plugin_symlinks/audioplayers_linux
  linux/flutter/ephemeral/.plugin_symlinks/connectivity_plus
  linux/flutter/ephemeral/.plugin_symlinks/dynamic_color
  linux/flutter/ephemeral/.plugin_symlinks/package_info_plus
  linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
  linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
  linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugin_registrant.h
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  macos/Flutter/ephemeral/flutter_export_environment.sh
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugin_registrant.h
  windows/flutter/generated_plugins.cmake
Labels: size/L

#32 fix: topic subscription
  .devcontainer/devcontainer.json
  lib/core/api.dart
  lib/view/earthquake.dart
  lib/view/init.dart
  lib/view/me.dart
Labels: size/L

#33 Create FUNDING.yml
  .github/FUNDING.yml
Labels: size/S

#34 fix: api url
  lib/core/api.dart
Labels: size/S

#35 bump: v1.1.5
  pubspec.yaml
Labels: size/XS

#36 release: v1.1.5
  .devcontainer/devcontainer.json
  .github/FUNDING.yml
  .gitignore
  lib/core/api.dart
  lib/view/earthquake.dart
  lib/view/init.dart
  lib/view/loc-set.dart
  lib/view/me.dart
  linux/flutter/ephemeral/.plugin_symlinks/audioplayers_linux
  linux/flutter/ephemeral/.plugin_symlinks/connectivity_plus
  linux/flutter/ephemeral/.plugin_symlinks/dynamic_color
  linux/flutter/ephemeral/.plugin_symlinks/package_info_plus
  linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
  linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
  linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugin_registrant.h
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  macos/Flutter/ephemeral/flutter_export_environment.sh
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugin_registrant.h
  windows/flutter/generated_plugins.cmake
Labels: release, size/XL

#37 fix: location setting
  lib/core/fcm.dart
  lib/core/utils.dart
  lib/global.dart
  lib/model/area_intensity.dart
  lib/model/earthquake_report.dart
  lib/model/partial_earthquake_report.dart
  lib/model/station_intensity.dart
  lib/model/town.dart
  lib/view/earthquake.dart
  lib/view/history.dart
  lib/view/home.dart
  lib/view/init.dart
  lib/view/me.dart
  lib/view/radar.dart
  lib/view/setting/ios/cupertino_city_page.dart
  lib/widget/drag_handle.dart
Labels: size/L

#38 feature: eew box
  lib/core/utils.dart
  lib/util/intensity_color.dart
  lib/view/earthquake.dart
Labels: size/XL

#40 fix: map marker layers
  lib/view/report.dart
Labels: size/L, enhancement, android, ios

#41 bump: v1.2.1
  pubspec.yaml
Labels: size/XS

#43 feat: report list magnitude
  lib/util/mag_color.dart
  lib/widget/earthquake_report_list_tile.dart
Labels: size/L

#44 fix: capsule text color on ios
  lib/widget/report/intensity_capsule.dart
Labels: size/XS, ios

#45 refactor: eew
  lib/core/api.dart
  lib/core/utils.dart
  lib/model/eew.dart
  lib/model/eew_info.dart
  lib/model/wave_time.dart
  lib/util/parser.dart
  lib/view/earthquake.dart
  lib/view/me.dart
  lib/view/setting/ios/cupertino_town_page.dart
Labels: android, ios, size/XXL

#46 feat: report list detail
  lib/view/report_list.dart
  lib/widget/earthquake_report_list_tile.dart
Labels: size/M, android

#42 release: v1.2.1
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  lib/core/api.dart
  lib/core/fcm.dart
  lib/core/utils.dart
  lib/global.dart
  lib/model/area_intensity.dart
  lib/model/earthquake_report.dart
  lib/model/eew.dart
  lib/model/eew_info.dart
  lib/model/partial_earthquake_report.dart
  lib/model/station_intensity.dart
  lib/model/town.dart
  lib/model/wave_time.dart
  lib/util/intensity_color.dart
  lib/util/mag_color.dart
  lib/util/parser.dart
  lib/view/earthquake.dart
  lib/view/history.dart
  lib/view/home.dart
  lib/view/image_viewer.dart
  lib/view/init.dart
  lib/view/me.dart
  lib/view/radar.dart
  lib/view/report.dart
  lib/view/report_list.dart
  lib/view/setting/ios/cupertino_city_page.dart
  lib/view/setting/ios/cupertino_town_page.dart
  lib/widget/drag_handle.dart
  lib/widget/earthquake_report_list_tile.dart
  lib/widget/report/image_field.dart
  lib/widget/report/intensity_capsule.dart
  pubspec.lock
  pubspec.yaml
Labels: release, size/XXL

#48 feat: ios check for updates
  ios/Podfile
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  lib/widget/earthquake_report_list_tile.dart
Labels: size/M, ios

#50 fix: url
  lib/core/api.dart
Labels: size/S

#51 fix: magnitude text
  lib/util/intensity_color.dart
  lib/util/mag_color.dart
  lib/util/magnitude_color.dart
  lib/widget/earthquake_report_list_tile.dart
Labels: size/L, android, ios

#52 docs: App Stoer privacy policy
  ios/Runner/PrivacyInfo.xcprivacy
Labels: size/XS, ios

#56 fix: gesture navigation bar completely transparent
  lib/main.dart
Labels: size/XS, android

#66 Fix: eew screen display
  lib/view/earthquake.dart
Labels: size/M, android, ios

#67 feat: donation link
  lib/view/me.dart
Labels: size/S

#74 fix: map provider
  assets/tw_city.geojson
  lib/global.dart
  lib/view/report.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L, android, ios
