Repository ExpTechTW/DPIP, pull requests merged in 2024-06, with the labels that each got.

#77 chore: add more help sections
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/view/about_rts.dart
  lib/view/about_state.dart
  lib/view/me.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L, 增強, p2

#86 feat: switch to map
  lib/core/api.dart
  lib/model/intensity_listing.dart
  lib/model/rts.dart
  lib/model/rts_station.dart
  lib/model/station.dart
  lib/model/station_info.dart
  lib/util/instrumental_intensity_color.dart
  lib/util/intensity_color.dart
  lib/view/earthquake.dart
  lib/view/report.dart
  lib/widget/earthquake_report_list_tile.dart
  lib/widget/report/intensity_capsule.dart
Labels: size/L, android, ios, p2

#87 feat: home page
  assets/dist_code.json
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/core/api.dart
  lib/global.dart
  lib/model/weather_air.dart
  lib/model/weather_feel.dart
  lib/model/weather_gust.dart
  lib/model/weather_precip.dart
  lib/model/weather_pressure.dart
  lib/model/weather_realtime.dart
  lib/model/weather_temp.dart
  lib/model/weather_vis.dart
  lib/model/weather_wind.dart
  lib/view/home_page.dart
  lib/view/init.dart
  lib/view/weather_warning.dart
  lib/widget/home_page_info.dart
  lib/widget/home_page_weather.dart
  pubspec.lock
  pubspec.yaml
Labels: android, ios, size/XXL

#92 fix: popup message
  lib/view/me.dart
Labels: size/S, ios

#91 feat: P&S wave map
  lib/view/earthquake.dart
  pubspec.lock
  pubspec.yaml
Labels: size/XL, 增強, android, ios, p2

#79 refactor: Audio UI
  .gitignore
  README.md
  lib/view/me.dart
  lib/view/notify.dart
Labels: size/XL, android, ios

#97 Revert "refactor: Audio UI"
  .gitignore
  README.md
  lib/view/me.dart
  lib/view/notify.dart
Labels: size/XL

#93 docs: md
  README.md
Labels: size/S

#98 fix: ios手機排版
  lib/widget/home_page_weather.dart
Labels: size/XS, ios

#104 feat:新增官網按鈕
  lib/view/me.dart
Labels: size/S

#103 fix: map
  pubspec.lock
  pubspec.yaml
Labels: size/S, ios, p0

#101 fix: iOS boundary
  lib/view/home_page.dart
Labels: size/L, ios, p3

#100 feat: earthquake time
  lib/view/earthquake.dart
  lib/view/report.dart
Labels: size/S, 增強, p3

#105 feat:新增系統狀態按鈕
  lib/view/me.dart
Labels: size/M

#106 fix: text position
  lib/view/earthquake.dart
Labels: size/S, ios

#96 refactor: Audio UI
  assets/eq.wav
  assets/info.wav
  assets/normal.wav
  assets/rain.wav
  assets/report.wav
  assets/tsunami.wav
  assets/warn.wav
  assets/weather.wav
  lib/view/me.dart
  lib/view/notify.dart
  lib/widget/play_button.dart
  lib/widget/sound_button.dart
  lib/widget/title_text.dart
  pubspec.lock
  pubspec.yaml
Labels: size/XL, 增強, android, ios, p1

#99 feat: Welcome page
  assets/DPIP.png
  assets/tos.md
  lib/main.dart
  lib/view/home_page.dart
  lib/view/init.dart
  lib/view/welcome/welcome.dart
  lib/view/welcome/welcome_earthquake.dart
  lib/view/welcome/welcome_note.dart
  lib/view/welcome/welcome_notify.dart
  pubspec.lock
  pubspec.yaml
Labels: 增強, size/XXL, p1

#108 perf: api
  lib/core/api.dart
  lib/view/earthquake.dart
Labels: size/S, p2

#107 "強震監視器"內容
  lib/view/notify.dart
Labels: size/XS, p2

#109 feat: ios important tips to know
  assets/important_hint.md
  lib/view/welcome/welcome_earthquake.dart
  lib/view/welcome/welcome_note.dart
  lib/view/welcome/welcome_notify.dart
  pubspec.yaml
Labels: size/M, ios, p2

#111 fix: AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
Labels: size/XS

#112 fix: weather icon
  lib/widget/home_page_weather.dart
Labels: size/M

#110 feat: First time installation Jump to location page
  lib/view/home_page.dart
Labels: size/M, 增強, ios

#113 main
  lib/view/home_page.dart
  lib/widget/home_page_weather.dart
Labels: size/L

#122 Update Bug.md
  .github/ISSUE_TEMPLATE/Bug.md
Labels: size/M

#129 fix: location
  .gitignore
  lib/core/service.dart
  lib/main.dart
  lib/route/settings/content/location.dart
Labels: size/M
