Repository ExpTechTW/DPIP, pull requests merged in 2024-10, with the labels that each got.

#286 i18n.dpip
  lib/app/page/map/meteor.dart
  lib/l10n/app_zh_TW.arb
Labels: size/S

#284 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh_CN.arb
Labels: size/XL

#279 feat: auto start and battery optimization permission denied
  android/app/build.gradle
  lib/l10n/app_zh_TW.arb
  lib/route/settings/content/location.dart
  lib/route/welcome/pages/permission.dart
  pubspec.yaml
Labels: size/L, android
