Repository ExpTechTW/DPIP, pull requests merged in 2024-07, with the labels that each got.

#130 feat: location settings
  .gitignore
  ios/Podfile
  ios/Runner/AppDelegate.swift
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  ios/Runner/Info.plist
  lib/core/location.dart
  lib/core/notify.dart
  lib/core/service.dart
  lib/main.dart
  lib/model/map_config.dart
  lib/model/map_config.freezed.dart
  lib/model/map_style.dart
  lib/model/map_style.g.dart
  lib/route/report/report.dart
  lib/route/settings/content/location.dart
  lib/widget/report/list_item.dart
  macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  macos/Flutter/ephemeral/flutter_export_environment.sh
  pubspec.lock
  pubspec.yaml
Labels: size/XXL

#140 bump: 2.0.12
  .github/workflows/github_actions.yml
  ios/Runner.xcodeproj/project.pbxproj
  lib/core/location.dart
  lib/core/service.dart
  lib/main.dart
  lib/route/settings/content/location.dart
  pubspec.yaml
Labels: size/S

#142 Test ios location
  ios/Runner/AppDelegate.swift
  ios/Runner/Services/FirebaseService.swift
  ios/Runner/Services/LocationManager.swift
Labels: size/L

#141 feat: manual location selector
  assets/location.json
  lib/app/page/me/me.dart
  lib/global.dart
  lib/model/location/location.dart
  lib/route/location_selector/location_selector.dart
  lib/route/location_selector/search.dart
  lib/route/settings/content/location.dart
  pubspec.yaml
Labels: size/L

#143 feat: tsunami data model
  lib/model/tsunami/tsunami.dart
  lib/model/tsunami/tsunami_actual.dart
  lib/model/tsunami/tsunami_earthquake.dart
  lib/model/tsunami/tsunami_estimate.dart
  lib/model/tsunami/tsunami_info.dart
Labels: size/L

#144 merge: from main
  .github/pull_request_template.md
  assets/location.json
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/AppDelegate.swift
  lib/app/page/home/home.dart
  lib/app/page/me/me.dart
  lib/core/fcm.dart
  lib/core/location.dart
  lib/core/notify.dart
  lib/core/service.dart
  lib/global.dart
  lib/main.dart
  lib/model/location/location.dart
  lib/model/map_style.g.dart
  lib/model/tsunami/tsunami.dart
  lib/model/tsunami/tsunami_actual.dart
  lib/model/tsunami/tsunami_earthquake.dart
  lib/model/tsunami/tsunami_estimate.dart
  lib/model/tsunami/tsunami_info.dart
  lib/route/location_selector/location_selector.dart
  lib/route/location_selector/search.dart
  lib/route/report/report.dart
  lib/route/settings/content/location.dart
  macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  macos/Flutter/ephemeral/flutter_export_environment.sh
  pubspec.yaml
Labels: size/XXL

#145 feat: auto-location-send
  lib/route/settings/content/location.dart
Labels: size/S

#146 fix: auto-location-Turn-off-bug
  lib/route/settings/content/location.dart
Labels: size/XS

#147 Fix auto location turn off bug
  lib/route/settings/content/location.dart
  pubspec.yaml
Labels: size/XS

#149 fix: github action
  .github/workflows/github_actions.yml
  android/app/build.gradle
Labels: size/XS

#150 Refactor
  .gitignore
  lib/model/map_style.dart
  lib/model/map_style.g.dart
  pubspec.lock
  pubspec.yaml
Labels: size/M

#152 feat: Tsunami UI
  lib/api/exptech.dart
  lib/api/route.dart
  lib/app/dpip.dart
  lib/app/page/map/map.dart
  lib/app/page/map/tsunami.dart
  lib/app/page/map/tsunami_estimate_list.dart
  lib/app/page/map/tsunami_observed_list.dart
  lib/l10n/app_en.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_TW.arb
  lib/model/tsunami/tsunami_actual.dart
  lib/model/tsunami/tsunami_estimate.dart
  lib/model/tsunami/tsunami_list.dart
Labels: size/XL

#156 feat: IOS forced update
  ios/Podfile
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
Labels: size/S, ios, p4

#155 Feat auto start permission
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/app/dpip.dart
  lib/core/service.dart
  lib/route/settings/content/location.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#154 137 dev audio UI
  assets/Int_report.wav
  assets/eew.wav
  assets/eew_alert.wav
  assets/eq.wav
  assets/info.wav
  assets/normal.wav
  assets/rain.wav
  assets/report.wav
  assets/tsunami.wav
  assets/update.wav
  assets/warn.wav
  assets/weather.wav
  ios/Podfile.lock
  lib/route/settings/content/Audio.dart
  lib/route/settings/content/root.dart
  lib/route/settings/settings.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#157 fix: Store localization language
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/zh-Hant.lproj/LaunchScreen.strings
  ios/Runner/zh-Hant.lproj/Main.strings
Labels: size/S

#158 tsunami
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  assets/Int_report.wav
  assets/eew.wav
  assets/eew_alert.wav
  assets/eq.wav
  assets/info.wav
  assets/normal.wav
  assets/rain.wav
  assets/report.wav
  assets/tsunami.wav
  assets/update.wav
  assets/warn.wav
  assets/weather.wav
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  ios/Runner/zh-Hant.lproj/LaunchScreen.strings
  ios/Runner/zh-Hant.lproj/Main.strings
  lib/app/dpip.dart
  lib/core/service.dart
  lib/route/settings/content/Audio.dart
  lib/route/settings/content/location.dart
  lib/route/settings/content/root.dart
  lib/route/settings/settings.dart
  pubspec.lock
  pubspec.yaml
Labels: size/XL

#160 feat: copy-FCM-Token
  lib/route/settings/content/root.dart
  pubspec.lock
  pubspec.yaml
Labels: size/M

#161 feat: base map implementation
  assets/map/box.json
  assets/map/cn.json
  assets/map/jp.json
  assets/map/kp.json
  assets/map/kr.json
  assets/map/tw_county.json
  assets/map/tw_town.json
  lib/global.dart
  lib/model/map_config.dart
  lib/model/map_config.freezed.dart
  lib/model/map_style.dart
  lib/route/report/report.dart
  lib/util/extension/int.dart
  lib/widget/map/map.dart
  lib/widget/map/marker/custom_marker.dart
  lib/widget/map/marker/intensity_marker.dart
  lib/widget/map/marker/marker.dart
  lib/widget/report/list_item.dart
  macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  macos/Flutter/ephemeral/flutter_export_environment.sh
  pubspec.yaml
Labels: size/XXL

#162 refactor: settings route
  .gitignore
  lib/route/settings/content/Audio.dart
  lib/route/settings/content/location.dart
  lib/route/settings/content/root.dart
  lib/route/settings/content/sound.dart
  lib/route/settings/content/theme.dart
  lib/route/settings/settings.dart
  lib/widget/settings/sound/sound_list_tile.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: size/XXL

#163 Fix auto location
  .github/workflows/lock.yml
  android/app/src/main/res/raw/eew.wav
  android/app/src/main/res/raw/eew_alert.wav
  android/app/src/main/res/raw/eq.wav
  android/app/src/main/res/raw/info.wav
  android/app/src/main/res/raw/int_report.wav
  android/app/src/main/res/raw/normal.wav
  android/app/src/main/res/raw/rain.wav
  android/app/src/main/res/raw/report.wav
  android/app/src/main/res/raw/tsunami.wav
  android/app/src/main/res/raw/update.wav
  android/app/src/main/res/raw/warn.wav
  android/app/src/main/res/raw/weather.wav
  assets/int_report.wav
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/eew.wav
  ios/Runner/eew_alert.wav
  ios/Runner/eq.wav
  ios/Runner/info.wav
  ios/Runner/int_report.wav
  ios/Runner/normal.wav
  ios/Runner/rain.wav
  ios/Runner/report.wav
  ios/Runner/tsunami.wav
  ios/Runner/update.wav
  ios/Runner/warn.wav
  ios/Runner/weather.wav
  lib/api/exptech.dart
  lib/app/dpip.dart
  lib/core/location.dart
  lib/core/service.dart
  lib/main.dart
  lib/route/settings/content/location.dart
  lib/route/settings/content/root.dart
  lib/route/settings/content/sound.dart
  lib/widget/report/list_item.dart
  macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  macos/Flutter/ephemeral/flutter_export_environment.sh
  pubspec.yaml
Labels: size/L

#164 Refactor ios location
  .github/workflows/github_actions.yml
  ios/Runner/AppDelegate.swift
  lib/core/location.dart
  lib/core/service.dart
  lib/main.dart
  lib/route/report/report.dart
  lib/route/settings/content/location.dart
  lib/route/settings/content/root.dart
Labels: size/XL

#165 build: 2.0.25
  pubspec.yaml
Labels: size/XS

#166 chore: compress sound files
  android/app/src/main/res/raw/eew.wav
  android/app/src/main/res/raw/eew_alert.wav
  android/app/src/main/res/raw/eq.wav
  android/app/src/main/res/raw/info.wav
  android/app/src/main/res/raw/int_report.wav
  android/app/src/main/res/raw/normal.wav
  android/app/src/main/res/raw/rain.wav
  android/app/src/main/res/raw/report.wav
  android/app/src/main/res/raw/tsunami.wav
  android/app/src/main/res/raw/update.wav
  android/app/src/main/res/raw/warn.wav
  android/app/src/main/res/raw/weather.wav
  assets/eew.wav
  assets/eew_alert.wav
  assets/eq.wav
  assets/info.wav
  assets/int_report.wav
  assets/normal.wav
  assets/rain.wav
  assets/report.wav
  assets/tsunami.wav
  assets/update.wav
  assets/warn.wav
  assets/weather.wav
  ios/Runner/eew.wav
  ios/Runner/eew_alert.wav
  ios/Runner/eq.wav
  ios/Runner/info.wav
  ios/Runner/int_report.wav
  ios/Runner/normal.wav
  ios/Runner/rain.wav
  ios/Runner/report.wav
  ios/Runner/tsunami.wav
  ios/Runner/update.wav
  ios/Runner/warn.wav
  ios/Runner/weather.wav
  pubspec.yaml
Labels: size/M

#167 fix: iOS sound name
  .gitignore
  ios/Runner.xcodeproj/project.pbxproj
  lib/widget/report/list_item.dart
Labels: size/S

#168 Update README.md
  README.md
Labels: size/XS

#169 Fix tsunami UI
  lib/app/page/map/tsunami.dart
  lib/model/tsunami/tsunami.dart
Labels: size/XS

#171 fix: auto location precision
  lib/core/service.dart
Labels: size/XS

#173 fix-導覽列透明效果
  lib/main.dart
Labels: size/XS

#174 fix: android location button
  lib/route/settings/content/location.dart
  pubspec.lock
Labels: size/M

#175 build: 2.0.26
  pubspec.yaml
Labels: size/XS

#177 fix: loc position country
  lib/core/location.dart
Labels: size/XS

#176 feat: report page details
  assets/map/icons/cross.png
  assets/map/icons/intensity-1-dark.png
  assets/map/icons/intensity-1.png
  assets/map/icons/intensity-2-dark.png
  assets/map/icons/intensity-2.png
  assets/map/icons/intensity-3-dark.png
  assets/map/icons/intensity-3.png
  assets/map/icons/intensity-4-dark.png
  assets/map/icons/intensity-4.png
  assets/map/icons/intensity-5-dark.png
  assets/map/icons/intensity-5.png
  assets/map/icons/intensity-6-dark.png
  assets/map/icons/intensity-6.png
  assets/map/icons/intensity-7-dark.png
  assets/map/icons/intensity-7.png
  assets/map/icons/intensity-8-dark.png
  assets/map/icons/intensity-8.png
  assets/map/icons/intensity-9-dark.png
  assets/map/icons/intensity-9.png
  ios/Podfile
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/model/report/earthquake_report.dart
  lib/route/image_viewer/image_viewer.dart
  lib/route/report/report.dart
  lib/route/report/report_sheet_content.dart
  lib/route/settings/content/location.dart
  lib/util/depth_color.dart
  lib/util/extension/build_context.dart
  lib/util/magnitude_color.dart
  lib/util/map_utils.dart
  lib/widget/map/map.dart
  lib/widget/map/marker/custom_marker.dart
  lib/widget/map/marker/intensity_marker.dart
  lib/widget/map/marker/marker.dart
  lib/widget/report/enlargeable_image.dart
  lib/widget/report/list_item.dart
  lib/widget/report/report_detail_field.dart
  lib/widget/settings/theme/theme_radio_tile.dart
  lib/widget/sheet/bottom_sheet_drag_handle.dart
  pubspec.lock
  pubspec.yaml
Labels: size/XXL

#180 fix: report intensity chip spacing
  ios/Podfile.lock
  lib/route/report/report_sheet_content.dart
Labels: size/XS

#179 fix: saved image not showing up in gallery
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/route/image_viewer/image_viewer.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#181 fix: map draw
  lib/route/report/report.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: size/S

#182 feat: Battery Optimization
  lib/route/settings/content/location.dart
  pubspec.lock
  pubspec.yaml
Labels: size/M

#183 fix: iOS Permissions
  ios/Runner/Info.plist
Labels: size/XS, ios

#184 fix: image viewer android permission
  android/app/src/main/AndroidManifest.xml
Labels: size/XS, android

#186 fix: location menu
  lib/route/settings/content/location.dart
Labels: size/XS

#190 feat: infinity scrolling
  lib/api/exptech.dart
  lib/api/route.dart
  lib/app/page/report_list/report_list.dart
Labels: size/M

#191 fix: restore listview bottom padding
  lib/route/settings/content/location.dart
  lib/route/settings/content/root.dart
  lib/route/settings/content/sound.dart
  lib/route/settings/content/theme.dart
  lib/util/extension/build_context.dart
Labels: size/S

#192 chore: change instagram to threads
  lib/app/page/me/me.dart
  lib/l10n/app_zh_TW.arb
  pubspec.lock
Labels: size/M

#187 feat: android send position
  lib/core/location.dart
  lib/core/service.dart
  lib/route/image_viewer/image_viewer.dart
Labels: size/M, android

#189 feat: monitor page
  assets/box.json
  assets/time.json
  lib/api/exptech.dart
  lib/api/route.dart
  lib/app/dpip.dart
  lib/app/page/monitor/monitor.dart
  lib/core/eew.dart
  lib/core/rts.dart
  lib/global.dart
  lib/main.dart
  lib/model/rts/rts.dart
  lib/model/rts/rts_intensity.dart
  lib/model/rts/rts_station.dart
  lib/model/town.dart
  lib/route/image_viewer/image_viewer.dart
  lib/route/report/report.dart
  lib/route/report/report_sheet_content.dart
  lib/util/instrumental_intensity_color.dart
  lib/util/map_utils.dart
  lib/widget/map/map.dart
  macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  macos/Flutter/ephemeral/flutter_export_environment.sh
  pubspec.yaml
Labels: size/XXL

#195 i18n(ReportRoute): tokenize texts
  lib/l10n/app_zh_TW.arb
  lib/route/report/report_sheet_content.dart
  lib/widget/report/list_item.dart
Labels: size/L

#197 Fix monitor page map
  lib/app/dpip.dart
  lib/app/page/monitor/monitor.dart
  lib/widget/map/map.dart
  macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  macos/Flutter/ephemeral/flutter_export_environment.sh
Labels: size/L

#196 fix: android send position
  lib/core/service.dart
Labels: size/XS

#198 fix: notify body
  lib/core/service.dart
Labels: size/XS

#194 fix: audio UI content
  lib/route/settings/content/sound.dart
Labels: size/S

#199 build: 2.0.29
  pubspec.yaml
Labels: size/XS

#201 fix: report route
  lib/app/page/report_list/report_list.dart
  lib/model/report/earthquake_report.dart
  lib/model/report/partial_earthquake_report.dart
  lib/route/report/report.dart
  lib/route/report/report_sheet_content.dart
  lib/util/extension/build_context.dart
  lib/util/parser.dart
  lib/widget/report/list_item.dart
Labels: size/XL

#200 fix: off auto position no remove
  lib/core/service.dart
  lib/route/settings/content/location.dart
Labels: size/L

#206 fix: android notify sound
  android/app/src/main/res/eew.wav
  android/app/src/main/res/eew_alert.wav
  android/app/src/main/res/eq.wav
  android/app/src/main/res/info.wav
  android/app/src/main/res/int_report.wav
  android/app/src/main/res/normal.wav
  android/app/src/main/res/rain.wav
  android/app/src/main/res/report.wav
  android/app/src/main/res/tsunami.wav
  android/app/src/main/res/update.wav
  android/app/src/main/res/warn.wav
  android/app/src/main/res/weather.wav
  lib/core/notify.dart
Labels: size/S

#202 feat: report page tsunami
  lib/route/report/report.dart
  lib/util/extension/color_scheme.dart
Labels: size/M

#203 Fix monitor page tray
  assets/map/icons/gps.png
  ios/Runner/AppDelegate.swift
  lib/app/page/monitor/eew_info.dart
  lib/app/page/monitor/monitor.dart
  lib/core/eew.dart
  lib/core/ios_get_location.dart
  lib/core/location.dart
  lib/core/rts.dart
  lib/route/location_selector/location_selector.dart
  lib/util/map_utils.dart
Labels: size/XL

#193 New Crowdin updates
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/en.lproj/LaunchScreen.strings
  ios/Runner/en.lproj/Main.strings
  ios/Runner/ja.lproj/LaunchScreen.strings
  ios/Runner/ja.lproj/Main.strings
  ios/Runner/ko.lproj/LaunchScreen.strings
  ios/Runner/ko.lproj/Main.strings
  ios/Runner/zh.lproj/LaunchScreen.strings
  ios/Runner/zh.lproj/Main.strings
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_zh.arb
Labels: size/L

#208 fix: Global preference keys
  lib/core/location.dart
  lib/core/service.dart
  lib/route/settings/content/location.dart
Labels: size/M

#209 fix: sheet key
  lib/route/report/report.dart
  pubspec.yaml
Labels: size/XS

#211 fix: time ui color
  lib/app/page/monitor/monitor.dart
  pubspec.yaml
Labels: size/XS
