Repository ExpTechTW/DPIP, pull requests merged in 2024-05, with the labels that each got.

#76 feat: ios earthquake list lists ML and depth
  lib/widget/earthquake_report_list_tile.dart
Labels: size/XS, ios, p2

#75 fix: ios map basemap selection reset
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  lib/util/magnitude_color.dart
  lib/view/me.dart
  lib/view/report.dart
  lib/view/setting/location.dart
  lib/widget/report/image_field.dart
Labels: size/L, ios, p3

#53 docs: App icon
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/108.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/234.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/258.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  lib/main.dart
Labels: size/M, android, ios, p2

#78 fix: ios depth
  lib/view/report.dart
  lib/view/report_list.dart
  lib/widget/earthquake_report_list_tile.dart
Labels: size/M, android, ios, p3

#80 feat: alert notify
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Runner.entitlements
  pubspec.yaml
Labels: size/S, 增強, ios, p1

#83 style: variable naming
  lib/core/utils.dart
  lib/view/history.dart
  lib/view/home.dart
Labels: size/L, p4

#85 chore: ios pod
  ios/Podfile.lock
  pubspec.lock
Labels: size/S

#88 feat: notify location api method
  lib/core/api.dart
Labels: size/S
