Repository ExpTechTW/DPIP, pull requests merged in 2025-07, with the labels that each got.

#312 ci: android-exclude-x86
  android/app/build.gradle
Labels: size/XS

#321 Updated Logo for TWDS
  README.md
Labels: size/XS

#335 New Crowdin updates
  assets/translations/en.po
  assets/translations/ja.po
  assets/translations/ko.po
  assets/translations/ru.po
  assets/translations/vi.po
  assets/translations/zh-Hans.po
Labels: size/XXL

#337 fix: notification navigation
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/core/fcm.dart
  lib/core/installation_tracker.dart
  lib/core/notify.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
Labels: size/L

#333 feat: telemetry
  ios/Podfile.lock
  lib/api/exptech.dart
  lib/api/route.dart
  lib/core/update.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#338 Build: 3.0.0
  CHANGELOG.md
  android/app/build.gradle
  pubspec.yaml
Labels: size/XS

#339 fix: notify_enabled
  lib/app/settings/notify/page.dart
Labels: size/XS

#341 fix(map/radar): radar layer
  lib/widgets/map/map.dart
Labels: size/S
