Repository ExpTechTW/DPIP, pull requests merged in 2025-02, with the labels that each got.

#294 chore: Android build
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  pubspec.yaml
Labels: size/S, android

#292 refactor: lb up to api v2
  lib/api/route.dart
  lib/widget/map/map.dart
Labels: size/XS

#290 fix: permission
  lib/route/welcome/pages/permission.dart
Labels: size/L

#287 New Crowdin updates
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh_CN.arb
Labels: size/L

#296 fix: typesetting
  lib/app/dpip.dart
  pubspec.yaml
Labels: size/XS

#297 fix: v2 time
  lib/api/exptech.dart
Labels: size/S

#299 fix: Tsunami wave height
  .github/workflows/github_actions.yml
  lib/app/page/map/tsunami/tsunami_estimate_list.dart
Labels: size/S

#301 Update README.md
  README.md
Labels: size/XS
