Repository ExpTechTW/DPIP, pull requests merged in 2025-08, with the labels that each got.

#345 chore: remove info log
  lib/app/map/_lib/managers/monitor.dart
  lib/app/map/_lib/managers/precipitation.dart
  lib/app/map/_lib/managers/radar.dart
  lib/app/map/_lib/managers/report.dart
  lib/app/map/_lib/managers/temperature.dart
  lib/app/map/_lib/managers/wind.dart
  lib/core/installation_tracker.dart
  lib/core/service.dart
  lib/main.dart
  lib/widgets/map/map.dart
Labels: size/M

#350 refactor: background service
  android/app/src/main/AndroidManifest.xml
  lib/api/exptech.dart
  lib/app/home/_widgets/eew_card.dart
  lib/app/home/_widgets/thunderstorm_card.dart
  lib/app/home/page.dart
  lib/app/map/_lib/managers/monitor.dart
  lib/app/map/_lib/managers/precipitation.dart
  lib/app/map/_lib/managers/radar.dart
  lib/app/map/_lib/managers/temperature.dart
  lib/app/settings/location/page.dart
  lib/app/settings/location/select/[city]/page.dart
  lib/app/settings/notify/page.dart
  lib/app_old/page/map/radar/radar.dart
  lib/core/ios_get_location.dart
  lib/core/location.dart
  lib/core/notify.dart
  lib/core/preference.dart
  lib/core/service.dart
  lib/core/update.dart
  lib/global.dart
  lib/main.dart
  lib/models/settings/location.dart
  lib/models/settings/map.dart
  lib/route/event_viewer/intensity.dart
  lib/route/event_viewer/thunderstorm.dart
  lib/utils/extensions/datetime.dart
  lib/utils/extensions/int.dart
  lib/utils/extensions/latlng.dart
  lib/utils/extensions/preference.dart
  lib/utils/extensions/string.dart
  lib/utils/geojson.dart
  lib/utils/location_to_code.dart
  lib/utils/map_utils.dart
  lib/widgets/map/map.dart
  pubspec.lock
  pubspec.yaml
Labels: size/XXL

#351 fix: label layer visibility when switching time
  lib/app/map/_lib/managers/precipitation.dart
Labels: size/XS

#352 feat: favorite locations
  lib/app/settings/location/page.dart
  lib/app/settings/location/select/[city]/page.dart
  lib/models/settings/location.dart
  lib/widgets/list/list_tile.dart
Labels: size/L

#353 feat: rts map values
  lib/app/map/_lib/managers/monitor.dart
  lib/models/data.dart
  lib/widgets/map/map.dart
Labels: size/L

#354 chore: improved startup time
  .github/workflows/ios.yml
  ios/Podfile.lock
  lib/global.dart
  lib/models/data.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#356 fix: map value placement & typing
  lib/api/model/report/earthquake_report.dart
  lib/api/model/report/partial_earthquake_report.dart
  lib/api/model/rts/rts.dart
  lib/api/model/station_intensity.dart
  lib/api/model/weather/rain.dart
  lib/api/model/weather/weather.dart
  lib/app/map/_lib/managers/monitor.dart
  lib/core/rts.dart
  lib/models/data.dart
  lib/route/report/report.dart
  lib/utils/extensions/latlng.dart
  lib/utils/map_utils.dart
  lib/widgets/map/map.dart
Labels: size/L

#358 Build: 3.0.200
  android/app/build.gradle
  pubspec.yaml
Labels: size/XS

#355 feat: click notifications
  lib/core/notify.dart
Labels: size/S

#363 feat: map style
  assets/sprites.json
  assets/sprites.png
  lib/app/map/page.dart
  lib/utils/extensions/maplibre.dart
  lib/widgets/map/map.dart
  lib/widgets/map/style.dart
  pubspec.lock
  pubspec.yaml
Labels: size/XXL

#360 fix: eew countdown
  lib/app/home/_widgets/eew_card.dart
  lib/app/map/_lib/managers/monitor.dart
Labels: size/XS

#364 refactor: map lifecycle
  lib/api/exptech.dart
  lib/api/route.dart
  lib/app.dart
  lib/app/home/_widgets/eew_card.dart
  lib/app/home/_widgets/radar_card.dart
  lib/app/home/page.dart
  lib/app/map/_lib/managers/monitor.dart
  lib/app/map/_lib/managers/precipitation.dart
  lib/app/map/_lib/managers/radar.dart
  lib/app/map/_lib/managers/temperature.dart
  lib/app/map/_lib/managers/tsunami.dart
  lib/app/map/_lib/managers/wind.dart
  lib/app/map/page.dart
  lib/app_old/dpip.dart
  lib/app_old/page/map/lightning/lightning.dart
  lib/app_old/page/map/radar/radar.dart
  lib/app_old/page/map/tsunami/tsunami.dart
  lib/app_old/page/map/typhoon/typhoon.dart
  lib/app_old/page/map/weather/humidity.dart
  lib/app_old/page/map/weather/pressure.dart
  lib/core/ios_get_location.dart
  lib/route/event_viewer/intensity.dart
  lib/route/event_viewer/thunderstorm.dart
  lib/utils/constants.dart
  lib/utils/extensions/int.dart
  lib/utils/extensions/latlng.dart
  lib/utils/extensions/maplibre.dart
  lib/utils/extensions/state.dart
  lib/utils/extensions/string.dart
  lib/utils/map_utils.dart
  lib/widgets/layout.dart
  lib/widgets/map/map.dart
  lib/widgets/map/style.dart
  pubspec.lock
  pubspec.yaml
Labels: size/XL

#342 New Crowdin updates
  assets/translations/en.po
  assets/translations/ja.po
  assets/translations/ko.po
  assets/translations/zh-Hans.po
Labels: size/XL

#371 fix: notify text
  assets/notify_test.json
  assets/translations/en.po
  assets/translations/ja.po
  assets/translations/ko.po
  assets/translations/ru.po
  assets/translations/strings.pot
  assets/translations/vi.po
  assets/translations/zh-Hans.po
  assets/translations/zh-Hant.po
  docs/sound.mdx
  lib/app/settings/notify/(3.weather)/evacuation/page.dart
  lib/app/settings/notify/(3.weather)/thunderstorm/page.dart
  lib/app/settings/notify/(4.tsunami)/tsunami/page.dart
  lib/app/settings/notify/page.dart
  lib/core/notify.dart
  lib/router.dart
Labels: size/L

#373 fix: ios service
  lib/core/service.dart
Labels: size/M

#376 fix(history): workandclassSuspension type
  lib/api/model/history/history.dart
  lib/widgets/home/event_list_route.dart
Labels: size/XS

#378 chore: move files
  .crowdin/location_names.csv
  .crowdin/strings.pot
  .crowdin/weather_station_names.csv
  assets/translations/location_names.csv
  assets/translations/weather_station_names.csv
  crowdin.yml
  l10n.yaml
  lib/l10n/app_en.arb
  lib/l10n/app_ja.arb
  lib/l10n/app_ko.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_vi.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_CN.arb
  lib/l10n/app_zh_TW.arb
  lib/utils/extensions/build_context.dart
  pubspec.yaml
  tools/update_translations.sh
Labels: size/XXL

#382 i18n: layer sheet use shorter term
  .crowdin/strings.pot
  assets/translations/en.po
  assets/translations/ja.po
  assets/translations/ko.po
  assets/translations/ru.po
  assets/translations/vi.po
  assets/translations/zh-Hans.po
  assets/translations/zh-Hant.po
  lib/app/map/_widgets/layer_toggle_sheet.dart
  tools/update_translations.sh
Labels: size/XXL

#383 New Crowdin updates
  assets/translations/en.po
  assets/translations/ja.po
  assets/translations/ko.po
  assets/translations/location_names.csv
  assets/translations/ru.po
  assets/translations/vi.po
  assets/translations/weather_station_names.csv
  assets/translations/zh-Hans.po
Labels: size/XXL

#385 fix: manager refresh data when shown
  lib/app/map/_lib/managers/precipitation.dart
  lib/app/map/_lib/managers/radar.dart
  lib/app/map/_lib/managers/report.dart
  lib/app/map/_lib/managers/temperature.dart
  lib/app/map/_lib/managers/wind.dart
Labels: size/L

#387 ci: Xcode
  .github/workflows/ios.yml
Labels: size/XS

#386 fix: i18n
  lib/app/settings/map/page.dart
Labels: size/XS

#388 fix: ios swipe back
  lib/app.dart
  lib/router.dart
  lib/utils/constants.dart
  lib/widgets/shell_wrapper.dart
  lib/widgets/transitions/forward_back.dart
  lib/widgets/transitions/predictive_fade_forward.dart
Labels: size/L, android, ios

#372 chore: organize code
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/en.lproj/InfoPlist.strings
  ios/Runner/vi.lproj/InfoPlist.strings
  lib/app/map/_lib/managers/radar.dart
  lib/app/map/_lib/managers/report.dart
  lib/app/settings/notify/page.dart
  lib/core/notify.dart
  lib/utils/depth_color.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L

#395 fix: eew
  lib/app/map/_lib/managers/monitor.dart
  lib/core/eew.dart
Labels: size/XS

#391 Flutter 3.35
  README.md
  android/app/build.gradle
  ios/Podfile.lock
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: size/M
