Repository ExpTechTW/DPIP, pull requests merged in 2025-09, with the labels that each got.

#397 fix: text size
  lib/app/home/_widgets/eew_card.dart
  lib/app/map/_lib/managers/monitor.dart
Labels: size/XS

#399 autostarter
  lib/app/settings/location/page.dart
  lib/app/welcome/4-permissions/page.dart
  pubspec.lock
  pubspec.yaml
Labels: size/M

#402 fix: city town with level
  android/app/build.gradle
  lib/models/data.dart
  lib/route/event_viewer/intensity.dart
  lib/route/event_viewer/thunderstorm.dart
  pubspec.yaml
Labels: size/S

#403 ci: storage cache
  .github/workflows/android.yml
  .github/workflows/ios.yml
Labels: size/M

#411 Add Claude Code GitHub Workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: size/L

#413 fix: background service timer
  CHANGELOG.md
  lib/core/service.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: size/S

#410 New Crowdin updates
  assets/translations/ja.po
Labels: size/M
